//===-- ashrqi3.S - Implement ___ashrqi3-----------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements ___ashrqi3 for the compiler_rt library.
//
//===----------------------------------------------------------------------===//


  .file  "ashrqi3.s"

  .text

  .globl  ___ashrqi3
  .type  ___ashrqi3,@function
___ashrqi3:

   cmp0 x
   bz   $.LBB_2
.LBB_1:
   sar  a, 1

   dec  x
   bnz  $.LBB_1
.LBB_2:
  ret
.Lfunc_end1:
  .size  ___ashrqi3, .Lfunc_end1- ___ashrqi3
